### ISSUE TITLE
OOP演習課題の作成

### ISSUE THREAD

**Issue by yamamoto-t** [M2O-Workshop/OMSB#14]
OOP要素の理解を底上げするため、演習課題を追加作成する。2月(3月)の集合研修で使用する。

**Comment by yamamoto-t** [comment]
@kyosukem 
@minaka-y 
@mizumoto-r 

OOP演習のたたき台としてTraining配下に雛形PGMを作成し、新規ブランチを切ってコミットしました。
・ブランチ名：feature-add-practiceOOP
・雛形PGM：/Training/sample/practiceOOP

また、補足のエクセル資料をm2oサーバーにuploadしてあります。（[wpdm_package id='645']）
http://wp.m2o-eiwa.1strentalserver.info/?wpdmpro=object%e6%8c%87%e5%90%91%e6%bc%94%e7%bf%92%e3%81%ae%e6%a4%9c%e8%a8%8e%e8%b3%87%e6%96%99&wpdmdl=645&masterkey=584d2cc789c56

ご確認／ご相談をお願いしたい点として、
　・そもそもの方向性と前提に認識相違がないか？
　・Interfaceの実現に際し、ラムダ式とレガシーなimplementsのどちらを使用（推奨）すべきか？
について、各位のご見解を頂戴したく。

ラムダ式とレガシーなimplementsの違いは上記エクセル資料に記載してあります。

よろしくお願いいたします！！

**Comment by yamamoto-t** [comment]
@M2O-Workshop/core-dev 

各位
OOP演習のたたき台「practiceOOP」について、リクエスト（？）にお応えし、
丸ごとMavenプロジェクト化しました。フォルダ構成もMavenの標準構成に合わせて、
大きく変更しています。

なお、初回のサーバーランタイム環境(Tomcat8+Java8の定義)だけは各自手動で設定が必要なため、
Trainingのwikiに補足ページを追加してあります。（Maven化できなくもなさそうですが、逆に超煩雑に。）
https://github.com/M2O-Workshop/Training

ついでに、サンプルとしてUTクラス+mockitoもMaven経由で実装済みです。これで、
　①Maven>プロジェクトの更新
　②実行>Maven clean
　③実行>Maven install
の3clickで環境構築～ビルド～テスト実施までが完了します。

ソースはブランチ切ってMaven化前とは別にしてありますので、
お手隙の折にpull&ワークスペースにimportしてみてください。
https://github.com/M2O-Workshop/Training/tree/feature-edit-practiceOOP-maven

ではでは、2017年もよろしくお願いしまーす。

**Comment by kyosukem** [comment]
@yamamoto-t 
おつかれ。
practiceOOPのソース見てみました。
ExcecuteLogicのexecメソッドですが、

```java:ExcecuteLogic.java
 public static ProposalEntity exec( ProposalEntity entity ) {

    // がん商品の場合
    if ( UnderWriteConst.PRODUCT_CANCER.equals( entity.getProduct() ) ) {
      // 査定処理を実行
      // ラムダ式記法（java.util.functionパッケージのtestメソッドを実装）
      entity.setResult( CancerUnderwrite.underWriteLogic.test( entity ) );
    }
    // 処理結果を返却する
    return EntityManager.createResultStr( entity );
  }
```

継承と多態性を使用することで、商品の判定を不要にできませんかね？
・CancerUnderwriteの継承元のクラスを用意して、その中でunderWriteLogicを持たせる。
・継承先のクラス（CancerUnderwrite）では、underWriteLogicをオーバーライドする。
・ExcecuteLogicでは、underWriteLogicを呼び出すが、多態性により商品の判断は不要。

ピント外れてますかね？？

**Comment by yamamoto-t** [comment]
@kyosukem 
新年、明けましておめでとうございます！
内容のご確認、ありがとうございました。

＞継承と多態性を使用することで、商品の判定を不要にできませんかね？
可能です。というわけで早速、修正してみました。

具体的には、動的にmodelインスタンスを生成するFactoryを噛ませることで、
ExcecuteLogicのexecメソッドから商品判定を排除し、underWriteLogicの呼び出しを共通化しました。

```java
      // modelを動的に生成
      AbstractUnderWrite model = ModelFactory.createModel( entity );
      // 査定処理を実行
      entity = model.underWriteLogic( entity );
```

あとOOP的なポイントとしては、Factoryからインスタンスを返却する以下の部分にも表れています。

```java
    // modelインスタンスを生成し返却する
    Class<?> cl = Class.forName( modelName.toString() );
    return ( AbstractUnderWrite ) cl.newInstance();
```
Interface型にキャストしていますが、インスタンスの実体は継承したサブクラスである、という点。
継承関係にあるクラス同士は型の指定にスーパークラス名を用いることで抽象化（＝汎用化）できる、
という機能（仕様）を利用しています。List系クラスでも日頃よく使う機能です。


別途PR送信しますので、認識相違ないか、改めてご確認願います！

**Comment by kyosukem** [comment]
議論をTrainingのIssue11(PR)に移します。
https://github.com/M2O-Workshop/Training/pull/11
