### ISSUE TITLE
OMSB開発環境におけるエンコードの選択

### ISSUE THREAD

**Issue by kyosukem** [M2O-Workshop/OMSB#2]
UTF-8にするか、Shift-JISにするか。Shift-JISが一般的のようですが、MACやLinuxを使っているメンバへのケアを考えるとちょっと検討する必要がありそうです。
取り急ぎ、水元にMACの環境でShift-JISが使えるか確認してもらいます。@mizumoto-r 
使えるようであれば、Shift-JISにしましょうか。

**Comment by mizumoto-r** [comment]
お疲れ様です。
Shift-JISは初期状態では文字コード一覧に出てきませんが、Shift-JISと手入力することで使えるようになるようです。
UTF-8で作成したサンプルプログラムをShift-JISに変えてビルドしたところ、正常に動きました。

**Comment by kyosukem** [comment]
では、Shift-JISを採用しましょう。

**Comment by kyosukem** [comment]
TraningリポジトリにおけるCSSが文字化けしているらしい。
Spring BootのデフォルトがUTF-8。MACも同様。
UTF-8にしましょうか？？

**Comment by yamamoto-t** [comment]
cssファイルでの日本語コメントの文字化けは、設定漏れが原因でした。
@CHARSET "UTF-8";（or @CHARSET "Shift_JIS";）をcssの先頭に記述することで解決。

併せて、文字コードについて色々調べてみました。
結論から言うと、OMSB開発は「UTF-8」で行きたいと思います。
（二転三転してしまい申し訳ありません。）

日本におけるソフトウェア開発において、国際標準である「UTF-8」への対応が
十分でなかった90年代～00年代までに構築されたOpen系システムでは、
文字データをバイト単位で効率的に扱えることもあり「SJIS」が広く用いられた模様です。

既に現在は日本の開発環境においても「UTF-8」への対応が進んでおり、
eclipse/Tomcat/SpringBoot/Git等々、OMSBでも使用することになる
各種ソフトウェアのデフォルトエンコードは「UTF-8」になっています。
＝「UTF-8」なら開発時に文字コード設定を殆ど意識せずに済む、という点もpointです。

また、データ効率という「SJIS」のメリットも、10年前や20年前の環境基準であり
当時とは比較にならないほどH/Wが進化している現在では、無視して良いレベルであると言えます。
むしろ「SJIS」は文字化けや誤動作の温床になり易く、リスクを内包することになります。

今回調べた限りでは、ネット上でも「近年のWeb開発では「UTF-8」が主流」との記述が多く、
敢えて今後システムを「SJIS」で構築するメリットは無いと判断しました。

以下、参考にしたサイトとなります。
http://tech.synchro-food.co.jp/entry/2016/02/29/213924
http://alaki.co.jp/blog/?p=1236
http://www.homepage-tukuri.com/shosinshanyuumon/entry70.html
他、各種wiki。

**Comment by kyosukem** [comment]
確認ありがとう。
了解です。UTF-8を採用しましょう！:dart:
#2をCloseします。
