### ISSUE TITLE
Spring Bootのサーバにおける稼働確認

### ISSUE THREAD

**Issue by kyosukem** [M2O-Workshop/OMSB#4]
OMSBではSpring Bootを採用予定ですが、レンタルサーバ関連の稼働確認を実施
確認が完了したら、各項目にチェックを入れてください。すべて終わったらCloseする。
- [x] サーバで動くか？？
- [x] warによるデプロイ
- [x] Spring Boot による MariaDB 接続
- [x] mavenによるサーバ上でのビルド
- [x] chkstyle の適用

**Comment by kyosukem** [comment]
@yamamoto-t 
山本くん、現在の状況にチェックを入れて、更新してもらえますか？完了しているようでしたらCloseお願いします！

**Comment by yamamoto-t** [comment]
お疲れ様です！山本です。
ステータスを更新しました。

上記の各項目を取り込んだ状態で
m2oサーバーのサンプルアプリを最新化済みですので、
お時間のある時に軽く叩いてみてください。

http://m2o-eiwa.1strentalserver.info/stsSample-0.0.1-SNAPSHOT/
※認証処理およびエラー処理はスカスカです。

なお、4つ目の「mavenによる"サーバ上"でのビルド」については利便性等を考慮して、
「maven+eclipseでローカル上でwarビルド⇒m2oサーバーのTomcatへデプロイ」で実施しています。
（少し調べたところ『外部サーバー上へのmaven導入～サーバー上でビルド』も技術的には可能なようですが、
　m2oサーバーはteraterm使用不可といった諸々の制約から厳しそうです。）

よろしくお願いいたします。

**Comment by kyosukem** [comment]
動いているの確認しました！
mavenについても、記載の方法で了解です。

1st社のサーバからeiwa本社サーバへの引っ越しもいずれ検討しますかね。
仮想化で実現しているらしいので学習コストがかかりますが、やりたい放題できるようになるかも。
これに関しては、（いつになるかわかりませんが）備忘のためのissueを挙げておきます。

**Comment by yamamoto-t** [comment]
早々のご確認、ありがとうございます！
少し中身を整理した上で、後ほどサンプルアプリのソースコードもGitHubでご連携します。

将来的な引っ越しについても承知いたしました。
現m2oサーバーの弱みは、つまりは共用サーバー故の弱みであると理解しています。

eiwa本社サーバーの他、
業者選定時に候補に挙がった専用サーバーやVPSも選択肢に入れつつ、
それぞれのメリデメを考慮していずれ検討させて頂きたいと思います。

よろしくお願いいたします。

**Comment by yamamoto-t** [comment]
お疲れ様です。※Reopenしてみます。

先ほどのサンプルのソースコードをGitHubにコミットしました。
https://github.com/m2oGIT/T_YamamotoRepository.git
「stsSample」

また、OMSBの共有リポジトリに環境構築用の資料をコミットしました。
https://github.com/M2O-Workshop/OMSB.git
「\doc\setting\01_StartUp\【m2o】SpringBoot+Maven_基礎知識と環境構築_v1.0.xlsx」

ご確認、よろしくお願いします。

**Comment by kyosukem** [comment]
1stserver社のサーバ上での稼働は確認できたので、当issueをCloseする。
