### ISSUE TITLE
JUnitを使用したUTの研修資料作成

### ISSUE THREAD

**Issue by kyosukem** [M2O-Workshop/OMSB#8]
勉強会においてUT方法の研修を実施する。そのための資料作り。

**Comment by mizumoto-r** [comment]
お疲れ様です。とりあえず、以下の構成で作り始めます。
①UTとは
　-概要
　-Open系のUTの特徴
　-主なプラグイン
②JUnitとは
　-概要
　-JUnitのメリット
　-JUnitのデメリット
　-JUnitの使用方法
③UTの流れ
　-テストクラスの作成
　-テストデータの作成
　-実行と結果確認
　-デバッグとPGM修正

**Comment by kyosukem** [comment]
おおむね良いと思います。
以下、盛り込んでほしい内容です。
・UTの特徴として、テストの自動化と、それがもたらす効果やメリットに主眼を置いてほしい。
　⇒レグレッションテストやリファクタリング等のやりやすさ等
・「主なプラグイン」はサラッとでよいと思います。
・WebアプリのUTの問題点や解決策も大事なテーマ
　⇒フレームワークの効果で、アプリをPOJOに近い形に実装できるので、テストもやりやすくなっている？
　⇒そもそも、UTしやすい設計・実装とは？

**Comment by mizumoto-r** [comment]
お疲れ様です。
作成中ですが、次のようなものを使っています。

[【M2O】UT資料20161225.zip](https://github.com/M2O-Workshop/OMSB/files/672125/M2O.UT.20161225.zip)

よろしくお願いいたします。

**Comment by kyosukem** [comment]
ザッと目を通しました。
まず、ファイル名が文字化けしています。MACで作成している影響かもしれません。

全般的に、内容が薄いです。
「概要」や「Open系のUTの特徴」は、もっと書くべきことがあるはずです。
　・サンプルコードが必要です。
　・assertやmatcherの言及は？
　・そもそも、テストケースはどう表現する？
　・今までの現場でのUTケース、テストクラスを例示する等の「実例」がないとイメージがわきません。

COBOLとJavaの両方で開発を体験しているのだから、両者の違いをもっと俯瞰的に説明するような
情報が絶対的に不足しています。
また、JavaでUTを実施するうえでのサンプルの例示がないと、伝わらないのでは？
せっかく「JUnit実践入門」を参照しているなら、そのエッセンスをもっと集約して盛り込むべきです。

以上、盛り込んでほしい内容です。

**Comment by yamamoto-t** [comment]
@M2O-Workshop/core-dev 

To:水元君
エクセル資料拝見しました。
蛇足ながら、資料の作り方について少々アドバイスを。

・せっかくExcelで作成しているのだから、Excelのメリットを活かしてみましょう。
　まずは羅列できる情報をマトリクス化したり、point箇所の文字色／セル色を変える辺りから。

　参考としては、以下のサイトなど。ググればいくらでも出てきます。
　http://enjoy.sso.biglobe.ne.jp/archives/excel_design/

・"概念(WHY)"と"手順(HOW)"が混在している（あるいは片方が欠けている）という印象を受けました。
　この２つは、説明の中で明確に分けた方が判り易いです。

　例えばcoverageも、Open系経験者と異なり、汎用機メンバにはさほど馴染みがない筈。
　ツールの導入方法の前に「そもそもcoverageとは何か、なぜcoverage計測するのか」を説明し、
　「Mockito」「EclEMMA」等の導入～使用方法は別シートに切り出す、といった構成がお勧めです。
　（＝読み手の視点、立場に立って資料を作成する。）

　coverageの考え方含め、以下サイトがまとめ方の参考になると思います。
　http://javaworld.helpfulness.jp/post-66/

・ファイル名の文字化けについては、山本端末(Windows10+64bit)でも然り。
　以下、化け方の参考までにls結果を添付しておきます。
　※ちなみにサブフォルダ「__MACOSX」配下のファイルは破損していて開けませんでした。

$ ls -lanR M2O.UT.20161225
M2O.UT.20161225:
total 1504
drwxr-xr-x 1 197614 197614       0 12月 31 20:22 ./
drwxr-xr-x 1 197614 197614       0 12月 31 20:22 ../
drwxr-xr-x 1 197614 197614       0 12月 31 20:22 __MACOSX/
-rw-r--r-- 1 197614 197614 1531904 12月 26 12:46 縲信2O縲繕T雉・侭.xls

M2O.UT.20161225/__MACOSX:
total 1
drwxr-xr-x 1 197614 197614   0 12月 31 20:22 ./
drwxr-xr-x 1 197614 197614   0 12月 31 20:22 ../
-rw-r--r-- 1 197614 197614 210 12月 26 12:46 ._縲信2O縲繕T雉・侭.xls


文献から得た情報を判り易くまとめる事はなかなか難しいと思いますが、
運営側として今後も必須となるスキルです。頑張っていきましょう。

以上、よろしくお願いいたします。

**Comment by mizumoto-r** [comment]
お疲れ様です。
JavaのUT資料を作成いたしました。レビュをお願い致します。
なお、総合演習で山本さんのサンプルアプリのプログラムのテストを入れようとしましたが、
どのプログラムを使うのがいいのかわかりませんでした。
申し訳ありませんが、お教えください。

[M2O_UT_Document.xlsx](https://github.com/M2O-Workshop/OMSB/files/801859/M2O_UT_Document.xlsx)

よろしくお願い致します。

**Comment by kyosukem** [comment]
水元の資料を確認しました。
テストを取り巻く時代の流れも取り上げたいし、JUnitによるUTそのものも取り上げたい。
水元の資料は、どちらかというとJUnitに特化しているように思います。
1日のカリキュラムでは網羅できないので、2回に分ける等のスケジュールも検討したい。

取り上げたいテーマは下記。近日中に、コナカで打ち合わせしましょうか。
１．開発プロセスから見たテストのアプローチ
　　・従来のウォーターフォールの問題点
　　・開発プロセスの見直しによる解決への取り組み　⇒CI等
　　・新しい開発プロセスを実現するためのテストの考え方
　　　　⇒自動化、再利用、テストしやすい設計、リファクタリング等

２．Javaにおける単体テストの実施
　　・Javaでの単体テストの単位　⇒クラス単位
　　・テストケースの設定　　　　⇒一般的なテスト技法に基づく
　　・カバレッジ　　　　　　　　⇒一般的なテスト技法に基づく
　　・テスト環境　　　　　　　　⇒ローカルPCに構築
　　・テスティングフレームワーク⇒JUnit、テストデータ、スタブ、モック

３．演習課題
　　・上記２の中に混ぜ込む

上記１は茂木の方で準備しようと思います。
水元の資料は、上記２,３を中心に再構成しましょう。（山本、サポートお願いします）

別途、連絡します。

**Comment by kyosukem** [comment]
本件、PracticeUTのissueへ議論を移します。
とうissueはClose。議論は
https://github.com/M2O-Workshop/PracticeUT/issues/2
で継続。
